### ISSUE TITLE
please add a screen

### ISSUE THREAD

**Issue by ojej** [ahosna/Pi0AudioBook#1]
Hello,
In my opinion You can add small 'screen' for example in binary mode show (small wood elements or not) which chapter are reading.  No needed more element. 8 small element (like uselles box) is ok.
Changing size of buttons (yellow,red etc) for better clarifi what device will to do.

**Comment by ahosna** [comment]
Thanks for the suggestion. Currently the chapter announcement is done by prefixing each audio file with chapter #1, so when you flick prev/next the first thing you hear is "chapter X". I've used https://www.speechtech.cz/speechtech-text-to-speech/speechtech-tts-online-demo/#Melanie210 to generate 200 "chapter X" files. They are checked in to the repo bu they are CZ/SK which fits my use case. Once audiobook is processed the chapter X becomes integral part of a sound file. 

As for the display, I'm not sure it would be worthwhile my use case. My "user" is old and doesn't have touch or mental capability to read braile. Instead for a next version I'm thinking of large repurposed PC screen hooked to RPI4. I'd mount the player to the screen and use both HDMI video and audio. Audio would be used to play radio/audio book and video would be used to get basic day information. Super large 4' high contrast text with date/time and day of week info.

Do you have an example of mechanical display ?

**Comment by ojej** [comment]
if You pased chapter and start again You probably dont remember witch chapter is playing.

No problem, any shape of 'screen' will be good. Ask user ;-) what they coding which chapter are playing. You are surprise. Yes I think about a few 'pixel' in mechanical screen. No more. Normal LCD are not comfortable for user and for other people near user. 
Machanical display are good options. If You can switching a switch it will be mechanical 'touch screen' ;-D

**Comment by ahosna** [comment]
If you pass a chapter, the next 5minute segment will tell you chapter N+1, also if you go next then prev it will again say chapter N. There is no seeking the the code. 5 minutes are fine to listen twice for my user. Good think is that chapter switching is fast. Holding next will skip next 10 chapters, holding prev will start at chapter 1 again. Play/pause works  and if you hold play it switches to a radio mode.
Super loud audio book playing is annoying. For the screen I have to solve a need for a calendar , but it's so hard to get good hi contrast calendars and I'm trying to get one every year. Large older TV screen would allow me to show massive calendar and would provide audio output as well. So basically player would then become integral part of this assistance screen. Just a thought now. Thanks for the feedback.
